USE nexus_db;

ALTER TABLE comments AUTO_INCREMENT = 1;
ALTER TABLE posts AUTO_INCREMENT = 1;
ALTER TABLE groups_nexus AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE sessions AUTO_INCREMENT = 1;